apiVersion: v1
kind: Service
metadata:
  name: kube-api-external
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 6443
      targetPort: 6443
      nodePort: 30643  # Выберите порт в диапазоне 30000-32767
  selector:
    component: kube-apiserver
