---
name: Docker Build and Deploy

on:
  push:
    tags:
      - "v*.*.*"  # Триггер на создание тегов вида vX.Y.Z

env:
  REGISTRY: docker.io
  IMAGE_NAME: sharvik40/nginx-app
  K8S_DEPLOYMENT: nginx-app-deployment
  K8S_NAMESPACE: default
  CONTAINER_NAME: nginx-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push with labels
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          labels: |
            version=${{ github.ref_name }}
            build.date=${{ github.run_number }}
            git.commit=${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v3
      
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.K8S_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "  insecure-skip-tls-verify: true" >> ~/.kube/config

      - name: Safe deployment update
        run: |
          # Получаем текущий deployment
          kubectl get deploy/${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }} \
            -o yaml > deployment.yaml \
            --insecure-skip-tls-verify
          
          # Обновляем версию образа
          sed -i "s|image:.*|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}|g" deployment.yaml
          
          # Применяем изменения
          kubectl apply -f deployment.yaml \
            -n ${{ env.K8S_NAMESPACE }} \
            --insecure-skip-tls-verify
          
          # Проверяем обновление
          kubectl rollout status deploy/${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }} \
            --insecure-skip-tls-verify \
            --timeout=300s

      - name: Verify deployment
        run: |
          echo "=== Deployment Status ==="
          kubectl get deploy/${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }} \
            -o wide \
            --insecure-skip-tls-verify
          
          echo ""
          echo "=== Running Pods ==="
          kubectl get pods \
            -n ${{ env.K8S_NAMESPACE }} \
            -l app=nginx-app \
            -o jsonpath='{range .items[*]}{.metadata.name}{": "}{.spec.containers[0].image}{"\n"}{end}' \
            --insecure-skip-tls-verify
