---
name: Docker Build and Deploy

on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: docker.io
  IMAGE_NAME: sharvik40/nginx-app
  K8S_DEPLOYMENT: nginx-app-deployment
  K8S_NAMESPACE: default
  CONTAINER_NAME: nginx-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: azure/setup-kubectl@v3
      
      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.K8S_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Full deployment update
        run: |
          set -x  # Включим отладку
          
          # 1. Обновляем образ (исправленный JSON с полной структурой)
          kubectl patch deployment/${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }} \
            --type=merge \
            --patch='{"spec":{"template":{"spec":{"containers":[{"name":"nginx-app","image":"'"${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}"'","imagePullPolicy":"Always"}]}}}' \
            --insecure-skip-tls-verify
          
          # 2. Проверяем статус
          kubectl rollout status deployment/${{ env.K8S_DEPLOYMENT }} \
            -n ${{ env.K8S_NAMESPACE }} \
            --insecure-skip-tls-verify \
            --timeout=300s

      - name: Verify deployment
        run: |
          echo "=== Current Deployment ==="
          kubectl get deployment/${{ env.K8S_DEPLOYMENT }} -n ${{ env.K8S_NAMESPACE }} -o yaml | grep -A 5 image:
          
          echo ""
          echo "=== Running Pods ==="
          kubectl get pods -n ${{ env.K8S_NAMESPACE }} -l app=nginx-app -o jsonpath='{range .items[*]}{.metadata.name}{": "}{.spec.containers[0].image}{"\n"}{end}'
