---
name: Docker Build and Deploy

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

env:
  REGISTRY: docker.io
  IMAGE_NAME: sharvik40/nginx-app
  K8S_NAMESPACE: default
  K8S_DEPLOYMENT: nginx-app

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest  # ← Фиксируем latest
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-k8s:
    name: Deploy to Kubernetes
    needs: build-and-push
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.K8S_CONFIG }}" | base64 -d > ~/.kube/config
          kubectl config use-context ${{ secrets.K8S_CONTEXT }}

      - name: Deploy to Kubernetes
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          kubectl -n ${{ env.K8S_NAMESPACE }} set image \
            deployment/${{ env.K8S_DEPLOYMENT }} \
            nginx=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$TAG
          kubectl -n ${{ env.K8S_NAMESPACE }} rollout status \
            deployment/${{ env.K8S_DEPLOYMENT }}
